// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6a17oTagL0q-DyAA3FBaXAqzUlTge6WI',
    appId: '1:412251136691:web:ad85d126c4de9487d4c6c6',
    messagingSenderId: '412251136691',
    projectId: 'clickcomprasapp',
    authDomain: 'clickcomprasapp.firebaseapp.com',
    storageBucket: 'clickcomprasapp.appspot.com',
    measurementId: 'G-KZY4Y1GJL6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMq1YF59XoaQw1YVHWftTy-lhUbB4jux8',
    appId: '1:412251136691:android:400155b657e2d0c6d4c6c6',
    messagingSenderId: '412251136691',
    projectId: 'clickcomprasapp',
    storageBucket: 'clickcomprasapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEu-tlGfZWKhQ9IzkkrlQdsebZXB8aeNQ',
    appId: '1:412251136691:ios:e5c4f47c73b66377d4c6c6',
    messagingSenderId: '412251136691',
    projectId: 'clickcomprasapp',
    storageBucket: 'clickcomprasapp.appspot.com',
    androidClientId: '412251136691-bv08k39l4vo8sfq11qf2b2ri8sm0gp92.apps.googleusercontent.com',
    iosClientId: '412251136691-93lm0cjbenq1bhf0ld8464eumgnov04v.apps.googleusercontent.com',
    iosBundleId: 'com.example.clickcompras',
  );

}